gh workflow run ddd-release-evidence.yml \
  -f mode=plan \
  -f strict=true \
  -f github_environment=staging \
  -f evidence_environment=staging \
  -f backend_base_url=__REQUIRED_HTTPS__ \
  -f frontend_base_url=__REQUIRED_HTTPS__ \
  -f ai_base_url= \
  -f max_artifact_age_hours=24 \
  -f expect_ai_remote=true \
  -f expect_frontend_deployed=true \
  -f promote_authenticated_baseline=false \
  -f baseline_accepted_by= \
  -f lane_completion_receipt_file= \
  -f lane_completion_receipt_base64=__REQUIRED_AFTER_COVERAGE_5_OF_5__
