create table if not exists `platform_module_definition` (
  `id` bigint not null auto_increment,
  `module_code` varchar(96) not null,
  `module_name` varchar(160) not null,
  `module_type` varchar(32) not null,
  `lifecycle_status` varchar(32) not null default 'PLANNED',
  `source_type` varchar(32) not null default 'DATABASE',
  `description` varchar(1000) default null,
  `owner_service` varchar(160) not null default 'system-service',
  `admin_route_path` varchar(255) default null,
  `api_prefixes` text default null,
  `permission_keys` text default null,
  `builtin` tinyint not null default 0,
  `sort_no` int not null default 0,
  `created_by` bigint not null default 0,
  `created_at` datetime not null default current_timestamp,
  `updated_by` bigint not null default 0,
  `updated_at` datetime not null default current_timestamp on update current_timestamp,
  `deleted` tinyint not null default 0,
  `version` bigint not null default 0,
  primary key (`id`),
  unique key `uk_platform_module_code` (`module_code`,`deleted`),
  key `idx_platform_module_type_status` (`module_type`,`lifecycle_status`,`deleted`),
  key `idx_platform_module_sort` (`sort_no`,`id`)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table if not exists `platform_module_dependency` (
  `id` bigint not null auto_increment,
  `module_code` varchar(96) not null,
  `dependency_module_code` varchar(96) not null,
  `min_version` varchar(64) default null,
  `optional_flag` tinyint not null default 0,
  `sort_no` int not null default 0,
  `created_by` bigint not null default 0,
  `created_at` datetime not null default current_timestamp,
  `updated_by` bigint not null default 0,
  `updated_at` datetime not null default current_timestamp on update current_timestamp,
  `deleted` tinyint not null default 0,
  primary key (`id`),
  unique key `uk_platform_module_dependency` (`module_code`,`dependency_module_code`,`deleted`),
  key `idx_platform_module_dependency_target` (`dependency_module_code`,`deleted`),
  key `idx_platform_module_dependency_sort` (`module_code`,`sort_no`,`id`)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
