CREATE TABLE IF NOT EXISTS platform_event_outbox (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NULL,
    source_type VARCHAR(64) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    event_key VARCHAR(128) NOT NULL,
    payload_json LONGTEXT NOT NULL,
    dispatch_status VARCHAR(32) NOT NULL DEFAULT 'RECORDED',
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME NULL,
    delivered_at DATETIME NULL,
    last_error VARCHAR(1024) NULL,
    trace_id VARCHAR(128) NULL,
    request_id VARCHAR(128) NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_platform_event_outbox_tenant_status (tenant_id, dispatch_status),
    KEY idx_platform_event_outbox_retry (dispatch_status, next_retry_at),
    KEY idx_platform_event_outbox_created_at (created_at),
    KEY idx_platform_event_outbox_event_key (event_key)
);
