package com.lumira.saas.modules.system.app;

import java.util.Set;

public final class SystemRouteCatalog {

    private static final Set<String> BUILT_IN_ROUTE_PATHS = Set.of(
            "/dashboard/home",
            "/data-management",
            "/data-management/download-center",
            "/data-management/query-center",
            "/activities",
            "/activities/management",
            "/activities/register",
            "/activities/search",
            "/competitions",
            "/competitions/management",
            "/competitions/registrations",
            "/competitions/review-results",
            "/competitions/create",
            "/competitions/register",
            "/competitions/expert-apply",
            "/registration",
            "/projects",
            "/projects/management",
            "/projects/search",
            "/payments",
            "/payments/management",
            "/payments/status",
            "/certificates",
            "/certificates/mine",
            "/certificates/templates",
            "/certificates/templates/:id/designer",
            "/certificates/generate",
            "/certificates/records",
            "/public/certificate/verify",
            "/certificate/verify/:publicToken",
            "/experts",
            "/experts/management",
            "/experts/query",
            "/expert-review",
            "/expert-review/reviews",
            "/workflows",
            "/workflows/tasks",
            "/workflows/config",
            "/system",
            "/system/overview",
            "/system/menus",
            "/system/dicts",
            "/system/profile-fields",
            "/system/personalization",
            "/system/sensitive-words",
            "/system/security",
            "/system/verification",
            "/system/smtp",
            "/system/notifications",
            "/system/plugins",
            "/system/monitoring",
            "/system/monitoring/service",
            "/system/monitoring/redis",
            "/system/monitoring/api-docs",
            "/system/monitoring/audit",
            "/system/files",
            "/system/files/my",
            "/system/files/all",
            "/files",
            "/files/all",
            "/team",
            "/team/management",
            "/team/search",
            "/team/create",
            "/team/join",
            "/team/:teamId",
            "/team/:teamId/members",
            "/team/:teamId/invites",
            "/settings",
            "/settings/overview",
            "/settings/menus",
            "/settings/dicts",
            "/settings/profile-fields",
            "/settings/personalization",
            "/settings/sensitive-words",
            "/settings/security",
            "/settings/verification",
            "/settings/payment",
            "/settings/smtp",
            "/settings/notifications",
            "/settings/plugins",
            "/settings/localization",
            "/settings/monitoring",
            "/settings/monitoring/service",
            "/settings/monitoring/redis",
            "/settings/monitoring/api-docs",
            "/settings/monitoring/audit",
            "/settings/api-docs",
            "/settings/audit",
            "/settings/files",
            "/settings/files/all",
            "/localization",
            "/work-order-feedback",
            "/user-center",
            "/user-center/users",
            "/user-center/departments",
            "/user-center/online-users",
            "/user-center/roles",
            "/user-center/personal-center",
            "/user-center/personal-center/profile",
            "/user-center/personal-center/files"
    );

    private static final Set<String> BUILT_IN_COMPONENT_PATHS = Set.of(
            "@/pages/dashboard/DashboardHomePage",
            "@/pages/DataManagementLandingPage",
            "redirect:/activities/register",
            "redirect:/activities/management",
            "redirect:/competitions/management",
            "redirect:/competitions/register",
            "redirect:/dashboard/home",
            "redirect:/payments/management",
            "redirect:/experts/management",
            "redirect:/certificates/mine",
            "redirect:/certificates/templates",
            "redirect:/expert-review/reviews",
            "redirect:/workflows/tasks",
            "@/pages/activity",
            "@/pages/competition",
            "@/pages/competition/CompetitionRegistrationDataPage",
            "@/pages/competition/CompetitionReviewResultsPage",
            "@/pages/project",
            "@/pages/payment",
            "@/pages/certificates/TemplatesPage",
            "@/pages/certificates/MyCertificatesPage",
            "@/pages/certificates/DesignerPage",
            "@/pages/certificates/GeneratePage",
            "@/pages/certificates/RecordsPage",
            "@/pages/certificates/PublicVerifyPage",
            "@/pages/expert",
            "@/pages/competition/CompetitionReviewPage",
            "@/pages/workflow/WorkflowTasksPage",
            "@/pages/workflow/WorkflowConfigPage",
            "@/layouts/SettingsLayout/SettingsLayout",
            "@/layouts/SettingsLayout",
            "@/pages/settings/menus",
            "@/pages/settings/dicts",
            "@/pages/settings/profile-fields",
            "@/pages/settings/personalization",
            "@/pages/plugins/SensitiveWordsPage",
            "@/pages/plugins/WorkOrderFeedbackPage",
            "@/pages/settings/security",
            "@/pages/settings/verification",
            "@/pages/settings/payment",
            "@/pages/settings/notifications/index",
            "@/pages/settings/notifications/NotificationsPage",
            "@/pages/settings/Plugins",
            "@/pages/settings/plugins",
            "@/pages/settings/plugins/PluginsPage",
            "@/pages/settings/monitoring/index",
            "@/pages/settings/monitoring/ApiDocs",
            "@/pages/settings/monitoring/MonitoringPage",
            "@/pages/settings/monitoring/Audit",
            "@/pages/settings/localization",
            "@/pages/settings/localization/LocalizationPage",
            "@/pages/settings/files/Center",
            "@/pages/user-center/index",
            "@/pages/iam/Overview",
            "@/pages/system/users",
            "@/pages/system/departments",
            "@/pages/system/online-users",
            "@/pages/system/roles",
            "@/pages/profile/Center",
            "@/pages/files/Center",
            "@/pages/files/DownloadCenter",
            "@/pages/team",
            "@/pages/audit/Overview",
            "@/pages/system/menus",
            "@/pages/system/Plugins",
            "@/pages/system/dicts",
            "@/pages/system/profile-fields",
            "@/pages/system/personalization",
            "@/pages/system/security",
            "@/pages/system/verification",
            "@/pages/system/notifications/index",
            "@/pages/system/monitoring/index",
            "@/pages/system/monitoring/ApiDocs",
            "@/pages/system/monitoring/Audit"
    );

    private SystemRouteCatalog() {
    }

    public static boolean isBuiltInMenuPath(String path) {
      return path != null && BUILT_IN_ROUTE_PATHS.contains(path.trim());
    }

    public static boolean isBuiltInMenuComponent(String component) {
        return component != null && BUILT_IN_COMPONENT_PATHS.contains(component.trim());
    }

    public static boolean isBuiltInMenu(com.lumira.saas.modules.system.vo.SystemVO.MenuVO menu) {
        if (menu == null) {
            return false;
        }
        if (menu.isBuiltin() && "BUTTON".equalsIgnoreCase(menu.getMenuType())) {
            return true;
        }
        return isBuiltInMenuPath(menu.getPath()) || isBuiltInMenuComponent(menu.getComponent());
    }
}
