CREATE TABLE IF NOT EXISTS `plugin_event_outbox` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `user_id` bigint DEFAULT NULL,
  `event_type` varchar(128) NOT NULL,
  `event_key` varchar(191) NOT NULL,
  `payload_json` json NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `retry_count` int NOT NULL DEFAULT 0,
  `next_retry_at` datetime DEFAULT NULL,
  `last_error_message` varchar(512) DEFAULT NULL,
  `created_by` bigint NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` bigint NOT NULL DEFAULT 0,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plugin_event_outbox_event` (`tenant_id`,`event_type`,`event_key`),
  KEY `idx_plugin_event_outbox_status` (`tenant_id`,`status`,`next_retry_at`),
  KEY `idx_plugin_event_outbox_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
