CREATE TABLE IF NOT EXISTS security_audit_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NULL,
    user_id BIGINT NULL,
    employee_id BIGINT NULL,
    event_type VARCHAR(128) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    source_ip VARCHAR(128) NULL,
    user_agent VARCHAR(512) NULL,
    request_id VARCHAR(128) NULL,
    trace_id VARCHAR(128) NULL,
    resource_code VARCHAR(128) NULL,
    action_code VARCHAR(64) NULL,
    target_id VARCHAR(128) NULL,
    result VARCHAR(32) NOT NULL,
    reason_code VARCHAR(128) NULL,
    message VARCHAR(1000) NULL,
    metadata_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_security_audit_created_at (created_at),
    KEY idx_security_audit_event_type_created_at (event_type, created_at),
    KEY idx_security_audit_tenant_created_at (tenant_id, created_at),
    KEY idx_security_audit_request_id (request_id),
    KEY idx_security_audit_source_ip_created_at (source_ip, created_at)
);
