saas:
  web:
    cors-allowed-origins: ${CORS_ALLOWED_ORIGINS}
    trust-forwarded-headers: ${TRUST_FORWARDED_HEADERS:true}
    trusted-proxy-cidrs: ${TRUSTED_PROXY_CIDRS}

spring:
  flyway:
    placeholders:
      defaultAdminInitEnabled: false
      defaultAdminPasswordHash: ${DEFAULT_ADMIN_PASSWORD_HASH:$2a$10$ko3RP4YpfVgyQC5pZjq5t.d1TKrqmBGoehczMjqn1k.pLeAAnTI9G}

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
