create table if not exists payment_provider_config (
    id bigint not null auto_increment primary key,
    tenant_id bigint not null,
    provider_code varchar(64) not null,
    provider_name varchar(128) not null,
    enabled tinyint(1) not null default 0,
    environment varchar(32) not null,
    encrypted_config_json longtext not null,
    configured tinyint(1) not null default 0,
    last_tested_at datetime null,
    last_test_success tinyint(1) null,
    last_test_message varchar(512) null,
    created_by bigint null,
    created_at datetime not null default current_timestamp,
    updated_by bigint null,
    updated_at datetime not null default current_timestamp on update current_timestamp,
    deleted tinyint(1) not null default 0,
    unique key uk_payment_provider_config_tenant_provider (tenant_id, provider_code),
    key idx_payment_provider_config_tenant_deleted (tenant_id, deleted),
    key idx_payment_provider_config_provider (provider_code)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists payment_order (
    id bigint not null auto_increment primary key,
    tenant_id bigint not null,
    order_no varchar(64) not null,
    provider_code varchar(64) not null,
    provider_order_no varchar(128) not null,
    subject varchar(255) not null,
    amount_minor bigint not null,
    currency varchar(16) not null,
    status varchar(32) not null,
    payment_url varchar(1024) null,
    client_ip varchar(64) null,
    notify_url varchar(1024) null,
    return_url varchar(1024) null,
    request_json longtext null,
    response_json longtext null,
    idempotency_key varchar(128) null,
    failure_code varchar(64) null,
    failure_message varchar(512) null,
    expires_at datetime null,
    paid_at datetime null,
    created_by bigint null,
    created_at datetime not null default current_timestamp,
    updated_by bigint null,
    updated_at datetime not null default current_timestamp on update current_timestamp,
    deleted tinyint(1) not null default 0,
    unique key uk_payment_order_tenant_order_no (tenant_id, order_no),
    unique key uk_payment_order_tenant_idempotency_key (tenant_id, idempotency_key),
    key idx_payment_order_tenant_status (tenant_id, status),
    key idx_payment_order_provider (tenant_id, provider_code, provider_order_no)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists payment_refund (
    id bigint not null auto_increment primary key,
    tenant_id bigint not null,
    refund_no varchar(64) not null,
    order_no varchar(64) not null,
    provider_code varchar(64) not null,
    provider_refund_no varchar(128) not null,
    amount_minor bigint not null,
    currency varchar(16) not null,
    status varchar(32) not null,
    reason varchar(255) not null,
    request_json longtext null,
    response_json longtext null,
    idempotency_key varchar(128) null,
    failure_code varchar(64) null,
    failure_message varchar(512) null,
    refunded_at datetime null,
    created_by bigint null,
    created_at datetime not null default current_timestamp,
    updated_by bigint null,
    updated_at datetime not null default current_timestamp on update current_timestamp,
    deleted tinyint(1) not null default 0,
    unique key uk_payment_refund_tenant_refund_no (tenant_id, refund_no),
    unique key uk_payment_refund_tenant_idempotency_key (tenant_id, idempotency_key),
    key idx_payment_refund_tenant_status (tenant_id, status),
    key idx_payment_refund_order_no (tenant_id, order_no)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists payment_webhook_event (
    id bigint not null auto_increment primary key,
    tenant_id bigint not null,
    provider_code varchar(64) not null,
    event_id varchar(128) not null,
    event_type varchar(128) not null,
    nonce varchar(128) null,
    request_timestamp varchar(64) null,
    payload_json longtext not null,
    signature varchar(2048) null,
    signature_valid tinyint(1) not null default 0,
    processed tinyint(1) not null default 0,
    process_message varchar(512) null,
    received_at datetime not null,
    processed_at datetime null,
    retry_count int not null default 0,
    next_retry_at datetime null,
    created_by bigint null,
    created_at datetime not null default current_timestamp,
    updated_by bigint null,
    updated_at datetime not null default current_timestamp on update current_timestamp,
    deleted tinyint(1) not null default 0,
    unique key uk_payment_webhook_event_tenant_provider_event (tenant_id, provider_code, event_id),
    key idx_payment_webhook_event_nonce (tenant_id, provider_code, nonce),
    key idx_payment_webhook_event_status (tenant_id, processed, retry_count)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists payment_event_outbox (
    id bigint not null auto_increment primary key,
    tenant_id bigint not null,
    user_id bigint null,
    source_type varchar(64) not null,
    event_type varchar(128) not null,
    event_key varchar(128) not null,
    payload_json longtext not null,
    status varchar(32) not null,
    retry_count int not null default 0,
    next_retry_at datetime null,
    last_error_message varchar(512) null,
    created_by bigint null,
    created_at datetime not null default current_timestamp,
    updated_by bigint null,
    updated_at datetime not null default current_timestamp on update current_timestamp,
    deleted tinyint(1) not null default 0,
    unique key uk_payment_outbox_event (tenant_id, source_type, event_type, event_key),
    key idx_payment_outbox_status (tenant_id, status, next_retry_at),
    key idx_payment_outbox_created_at (tenant_id, created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;
