global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: lumira-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - lumira-server-blue:8080
        labels:
          service_name: lumira-server
          slot: blue
      - targets:
          - lumira-server-green:8080
        labels:
          service_name: lumira-server
          slot: green

  - job_name: mysql
    static_configs:
      - targets:
          - mysqld-exporter:9104
        labels:
          service_name: mysql

  - job_name: backup-metrics
    static_configs:
      - targets:
          - backup-metrics-exporter:9100
        labels:
          service_name: mysql-backup

  - job_name: lumira-job-executor
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - lumira-job-executor:8080
        labels:
          service_name: lumira-job-executor

  - job_name: lumira-async
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - lumira-async:8080
        labels:
          service_name: lumira-async
