// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import ApartmentOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ApartmentOutlined';
import SafetyCertificateOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SafetyCertificateOutlined';
import AuditOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/AuditOutlined';
import UserOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/UserOutlined';
import SettingOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import AppstoreOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import TeamOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import SafetyOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SafetyOutlined';
import DatabaseOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/DatabaseOutlined';
import ControlOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ControlOutlined';
import ApiOutlined from '/Users/johntao/Documents/GitHub/legendary-invention/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ApiOutlined';
export default { DashboardOutlined, ApartmentOutlined, SafetyCertificateOutlined, AuditOutlined, UserOutlined, SettingOutlined, AppstoreOutlined, TeamOutlined, SafetyOutlined, DatabaseOutlined, ControlOutlined, ApiOutlined };
